services:    

    database:
            image: mcr.microsoft.com/mssql/server:2017-latest
            container_name: webstore-database
            expose:
                - 1433
            environment:
                SA_PASSWORD: "MyDB@123"
                ACCEPT_EULA: "Y"               

    api-identity:
        image: cclautert/webstore-identity-api:latest
        container_name: webstore-identity-api            
        restart: always
        expose:
            - 5101
        ports:
            - "5102:5102"
        environment: 
            ASPNETCORE_ENVIRONMENT: WebStore
            ASPNETCORE_URLS: http://+5101
            CUSTOMCONNSTR_DefaultConnection: "Server=database;Database=DSUsers;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer
        depends_on:
            - database

    api-catalog:
        image: cclautert/webstore-product-api:latest
        container_name: webstore-product-api        
        restart: always
        expose:
            - 5201
        ports:
            - "5202:5202"
        environment: 
            ASPNETCORE_ENVIRONMENT: WebStore
            ASPNETCORE_URLS: http://+5201
            CUSTOMCONNSTR_DefaultConnection: "Server=database;Database=DSCatalog;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer
        depends_on:
            - database