services:    

    database:
            image: mcr.microsoft.com/mssql/server:2017-latest
            container_name: webstore-database
            expose:
                - 1433
            environment:
                SA_PASSWORD: "MyDB@123"
                ACCEPT_EULA: "Y"               

    api-identity:
        image: cclautert/webstore-identity-api:latest
        container_name: webstore-identity-api            
        restart: always
        environment: 
            ASPNETCORE_ENVIRONMENT: WebStore
            ASPNETCORE_URLS: https://+:5101;http://+5102
            CUSTOMCONNSTR_DefaultConnection: "Server=database-identity;Database=DSUsers;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer
        depends_on:
            - database

    api-catalog:
        image: cclautert/webstore-product-api:latest
        container_name: webstore-product-api        
        restart: always
        environment: 
            ASPNETCORE_ENVIRONMENT: WebStore
            ASPNETCORE_URLS: https://+:5201;http://+5202
            CUSTOMCONNSTR_DefaultConnection: "Server=database-catalog;Database=DSCatalog;MultipleActiveResultSets=true;User Id=sa;Password=MyDB@123"
            AppSettings__DatabaseType: SqlServer
        depends_on:
            - database