version: "3"

services:

    sql-server:
        image: mcr.microsoft.com/mssql/server:2017-latest
        container_name: nerdstore-sql-server
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y"

    api-identidade:
        image: cclautert/webstore-identity-api:latest
        container_name: webstore-identity-api    
        build: 
            context: ../src
            dockerfile: ./services/WebStore.Identity.API/Dockerfile  
        restart: always    
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+5101
        volumes:
            - ./certs:/https:ro
        depends_on:
            - sql-server
            
    api-carrinho:
        image: cclautert/webstore-product-api:latest
        container_name: webstore-product-api
        build: 
            context: ../src
            dockerfile: ./services/WebStore.Product.API/Dockerfile      
        restart: always             
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+5201
        volumes:
            - ./certs:/https:ro
        depends_on:
            - sql-server